# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

source = ~/.local/share/dotfiles/default/hypr/monitors.conf
source = ~/.local/share/dotfiles/default/hypr/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/env.conf
source = ~/.local/share/dotfiles/default/hypr/input.conf
source = ~/.local/share/dotfiles/default/hypr/keybinds.conf
source = ~/.local/share/dotfiles/default/hypr/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/windowrules.conf
source = ~/.local/share/dotfiles/default/hypr/theme.conf
