### Monitors ###

# Change your personal monitor setup in here to keep the main config portable
# See https://wiki.hyprland.org/Configuring/Monitors/

# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=,preferred,auto,auto
