### General Settings ###

# Default applications
$terminal = ghostty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$passwordManager = bitwarden-desktop
$webapp = $browser --app
