[tools]
bob = "4.1.4"
go = "1.25.3"
gofumpt = "0.9.1"
lua-language-server = "3.15.0"
node = "25.0.0"
opencode = "0.15.8"
prettier = "3.6.2"
python = "3.14.0"
ruff = "0.14.1"
rust = "1.90.0"
stylua = "2.3.0"
uv = "0.9.4"
