[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]

[tools]
python = "3.13.7"
rust = "1.90.0"
go = "1.25.1"
uv = "0.8.22"
gofumpt = "0.9.1"
prettier = "3.6.2"
biome = "2.2.4"
lua-language-server = "3.15.0"
stylua = "2.3.0"
taplo = "0.10.0"
dprint = "0.50.2"
jq = "1.8.1"
node = "24.9.0"
