[tools]
bun = "1.2"
eza = "0.21"
fd = "10"
fzf = "0.61"
go = "1.23"
lazydocker = "0"
lazygit = "0.49"
lua-language-server = "3.13"
node = "22"
python = "3.13"
ripgrep = "14"
ruby = "3.4.3"
rust = "nightly"
stylua = "2"
zoxide = "0.9"
