programs:
    - lazydocker
    - lazygit
    - lazyvim:
        - if clipboard do not work:
            - xclip | xsel
    - kitty
    - tig
    - asdf
    - zsh
    - zap:
        - other options:
            - oh my zsh
    - luajit