services:
  db:
    image: postgres:17.4
    container_name: carriage_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: carriage
      POSTGRES_PASSWORD: carriage
    ports:
      - "5432:5432"

volumes:
  postgres_data:
