theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
scrolloff = 8

[editor.lsp]
auto-signature-help = false
display-signature-help-docs = false

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"

[keys.normal.g]
a = "code_action"

[keys.select]
A-u = "switch_to_lowercase"
A-S-u = "switch_to_uppercase"

[keys.insert]
C-s = ["normal_mode", ":w"]
