[language-server.ruff]
command = "ruff"
args = ["server"]
cmd_env = { RUFF_TRACE = 'messages' }

[language-server.ruff.config.settings]
logLevel = "debug"


[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config]
basedpyright.analysis.diagnosticMode = "openFilesOnly"
basedpyright.autoSearchPaths = false
basedpyright.useLibraryCodeForTypes = false
basedpyright.disableOrganizeImports = true

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]


# Languages


[[language]]
name = "typescript"
language-servers = ['vtsls', "vscode-eslint-language-server"]
formatter = { command = 'prettierd', args = [".ts"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff", "basedpyright"]
auto-format = true


[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }
