notARepository: "quit"
git:
  overrideGpg: true
os:
  editPreset: "nvim-remote"
pagers:
  - colorArg: always
    pager: diff-so-fancy
gui:
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - reverse
  border: rounded
  nerdFontsVersion: "3"
  skipDiscardChangeWarning: true
keybinding:
  files:
    commitChangesWithoutHook: <disabled>
