require('modules.mini')
require('modules.path')
require('modules.sources')
require('modules.lsp')
require('modules.theme')
require('modules.marks')

require('config.opts')
require('config.keymaps')
require('config.autocmds')

require('plugins.mini-files')
require('plugins.mini-keymaps')
require('plugins.fff')
require('plugins.grug-far')
require('plugins.venv-lsp')
require('plugins.mason')
require('plugins.treesitter')
require('plugins.snacks')
require('plugins.blink')
require('plugins.codecompanion')
require('plugins.conform')
require('plugins.crates')
require('plugins.rustacenvim')
require('plugins.mini-clue')
