set -s escape-time 0

set -g history-limit 10000
set -g base-index 1
set -g allow-rename on
set -g renumber-windows on
set -g default-terminal "${TERM}"
set -g mouse on
set -g set-titles on
set -g bell-action any
set -g visual-bell off
set -g visual-activity off
set -g focus-events on
set -g detach-on-destroy off

setw -g mode-keys vi
setw -g pane-base-index 1
setw -g monitor-activity on
setw -g aggressive-resize on

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -as terminal-features ",*:RGB"

set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-right "#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) "
set -g status-justify left

set-option -g status-left-length 200
set-option -g status-left " #{session_name}  "
set-option -g status-style "bg=default"
set-option -g window-status-format "#{window_index}:#{window_name}#{window_flags} "
set-option -g window-status-current-format "#{window_index}:#{window_name}#{window_flags} "
set-option -g window-status-current-style "fg=#e1a345"
set-option -g window-status-last-style "fg=#936a2e"
set-option -g window-status-activity-style none

# -r means that the bind can repeat without entering prefix again
# -n means that the bind doesn't use the prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf\; display-message 'config reloaded'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -n M-h previous-window
bind -n M-l next-window

bind -r H resize-pane -L 20
bind -r L resize-pane -R 20
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5

bind Space last-window
bind b switch-client -l
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind t new-window -c "#{pane_current_path}"
bind , command-prompt -I "#W" "rename-window '%%'"

bind-key S command-prompt -p "New session name:" "new-session -s '%%'"

bind s display-popup -E "\
    tmux list-sessions -F '#{session_name}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-session |\
    xargs tmux switch-client -t"

bind w display-popup -E "\
    tmux list-windows -F '#{window_index} #{window_name}' |\
    sed '/^$/d' |\
    fzf --reverse --header jump-to-window |\
    cut -d ' ' -f 1 |\
    xargs tmux select-window -t"
