unbind C-b
set -g prefix C-f
bind C-f send-prefix

# split panes using | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf \; display "Configuration reloaded."

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Move current window/tab left and right
bind-key S-Left swap-window -t -1
bind-key S-Right swap-window -t +1

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# tmux popup godies
bind-key j run-shell '~/.config/tmux/popup.sh'

# don't rename windows automatically
set-option -g allow-rename off

# rename session
bind . command-prompt -I "#S" "rename-session '%%'"

# Index based on 1, easier to reach on typical keyboards
set -g base-index 1
setw -g pane-base-index 1

# Make Prefix + 0 go to window number 10.
# Recall that I use window numberig starting from 1 instead of 0:
bind 0 select-window -t :10

# Automatically renumber windows
set -g renumber-windows on

# Increase tmux history
set -g history-limit 10000

# TrueColor
set -g  default-terminal   "xterm-256color"
set -sa terminal-overrides ',xterm-256color:RGB'

# Goyo :)
bind G set status

# Status bar at top
set -g status-position top
