#!/usr/bin/env bash

# Graphics card
CARD=`ls /sys/class/backlight | head -n 1`

# Get brightness
get_backlight() {
	if [[ "$CARD" == *"intel_"* ]]; then
		BNESS=`xbacklight -get`
		LIGHT=${BNESS%.*}
	else
		LIGHT=$(printf "%.0f\n" `light -G`)
	fi
	notify-send -t 1000 Light: ${LIGHT}%
}

# Increase brightness
inc_backlight() {
	if [[ "$CARD" == *"intel_"* ]]; then
		xbacklight -inc 10
		get_backlight
	else
		light -A 5
		get_backlight
	fi
}

# Decrease brightness
dec_backlight() {
	if [[ "$CARD" == *"intel_"* ]]; then
		xbacklight -dec 10
		get_backlight
	else
		light -U 5
		get_backlight
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]
    then
    get_backlight
    elif [[ "$1" == "--inc" ]]
    then
    inc_backlight
    elif [[ "$1" == "--dec" ]]
    then
    dec_backlight
else
    get_backlight
    fi
