#!/usr/bin/env bash
intern=eDP-1
extern=HDMI-1-0

# intern=eDP
# extern=HDMI-A-0

if xrandr | grep "$extern disconnected"
    then
    xrandr --output "$extern" --off --output "$intern" --auto
else
    xrandr --output "$intern" --off --output "$extern" --auto
fi
