### Shell Settings ###

# History control
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=32768
HISTFILESIZE="${HISTSIZE}"

# Set complete path
export PATH="./bin:$HOME/.local/bin:$HOME/.local/share/dotfiles/bin:$PATH"
set +h


### Environment Variables ###

if [ -n "$NVIM" ]; then
    export EDITOR="nvim --server $NVIM --remote"
    export SUDO_EDITOR="$EDITOR"
    export VISUAL="$EDITOR"
else
    export EDITOR="nvim"
    export SUDO_EDITOR="$EDITOR"
    export VISUAL="$EDITOR"
fi


### Aliases ###

#### File System Navigation ####
alias d='pwd'
alias ls='eza -lh --group-directories-first --icons=auto'
alias lsa='ls -A'
alias la="eza -lA"
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -A'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias fd='fdfind'
alias cd="zd"

zd() {
  if [ $# -eq 0 ]; then
    builtin cd ~ && return
  elif [ -d "$1" ]; then
    builtin cd "$1"
  else
    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
  fi
}

# Quick directory traversal
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

#### Tools and Utilities ####
alias nv="nvim"
alias lzd="lazydocker"
alias lzg="lazygit"
alias cl="clear"
alias ex="exit"

#### Git Commands ####
alias g="git"
alias gl="git log --all --oneline --graph --decorate"
alias gs="git status"
alias gd="git difftool --dir-diff"
alias gb="git branch"

#### File Compression ####
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

### Prompt Customization ###

# Technicolor dreams
force_color_prompt=yes
color_prompt=yes

# Simple prompt with path in the window/pane title and caret for typing line
PS1=$'\uf0a9 '
PS1="\[\e]0;\w\a\]$PS1"


### Initialization Scripts ###

if command -v mise &> /dev/null; then
  eval "$(mise activate bash)"
fi

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi

if command -v fzf &> /dev/null; then
  if [[ -f /usr/share/bash-completion/completions/fzf ]]; then
    source /usr/share/bash-completion/completions/fzf
  fi
  if [[ -f /usr/share/fzf/key-bindings.bash ]]; then
    source /usr/share/fzf/key-bindings.bash
  fi
fi
