# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

# Default applications
$terminal = ghostty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$passwordManager = bitwarden-desktop
$webapp = $browser --app

# Use defaults Dotfiles defaults
source = ~/.local/share/dotfiles/default/hypr/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/bindings.conf
source = ~/.local/share/dotfiles/default/hypr/envs.conf
source = ~/.local/share/dotfiles/default/hypr/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/input.conf
source = ~/.local/share/dotfiles/default/hypr/windows.conf
source = ~/.config/dotfiles/current/theme/hyprland.conf

# Extra env variables
env = GDK_SCALE,1 # Change to 1 if on a 1x display

# Extra env variables needed if running an NVIDIA GPU
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Start default apps
bind = SUPER, return, exec, $terminal
bind = SUPER, F, exec, $fileManager
bind = SUPER, B, exec, $browser
bind = SUPER, S, exec, $music
bind = SUPER, O, exec, $terminal -e btop
bind = SUPER, T, exec, typora
bind = SUPER, slash, exec, $passwordManager
bind = SUPER, P, exec, wofi --show drun --sort-order=alphabetical

# Extra Apps
bind = SUPER, C, exec, $webapp="https://app.hey.com/calendar/weeks/"
bind = SUPER, E, exec, $webapp="https://app.hey.com"
bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER, G, exec, $webapp="https://github.com/"
bind = SUPER, M, exec, $webapp="https://web.whatsapp.com/"
