# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

# Default applications
$terminal = alacritty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$passwordManager = bitwarden-desktop
$webapp = $browser --app

# Use defaults Dotfiles defaults
source = ~/.local/share/dotfiles/default/hypr/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/bindings.conf
source = ~/.local/share/dotfiles/default/hypr/envs.conf
source = ~/.local/share/dotfiles/default/hypr/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/input.conf
source = ~/.local/share/dotfiles/default/hypr/windows.conf
source = ~/.config/dotfiles/current/theme/hyprland.conf

# Extra env variables
env = GDK_SCALE,1 # Change to 1 if on a 1x display

# Extra env variables needed if running an NVIDIA GPU
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Extra bindings
bind = SUPER, C, exec, $webapp="https://app.hey.com/calendar/weeks/"
bind = SUPER, E, exec, $webapp="https://app.hey.com"
bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER SHIFT, G, exec, $webapp="https://web.whatsapp.com/"

input {
    kb_layout = us
    kb_variant = intl
    kb_options = grp:alt_space_toggle
}
