local set = vim.keymap.set

-- stylua: ignore start
set({ 'n', 'x', 'i' }, '<c-s>', '<esc><cmd>w<cr><esc>')
set({ 'i', 'x', 'n' }, '<esc>', '<esc><cmd>noh<cr><esc>')
set({ 'n', 'x'      }, 'j',     [[v:count == 0 ? 'gj' : 'j']], { expr = true })
set({ 'n', 'x'      }, 'k',     [[v:count == 0 ? 'gk' : 'k']], { expr = true })

set('x', 'p',     'P',         { noremap = true })
set('n', 'Y',     'v$<left>y', { desc = 'Copy till end of line' })
set('n', '<c-d>', '<c-d>zz',   { desc = 'Scroll downwards' })
set('n', '<c-u>', '<c-u>zz',   { desc = 'Scroll upwards' })
set('n', 'n',     'nzzzv',     { desc = 'Next result' })
set('n', 'N',     'Nzzzv',     { desc = 'Previous result' })
set('n', '*',     '*zzzv',     { desc = 'Previous result' })
set('n', '#',     '#zzzv',     { desc = 'Previous result' })

set('v', '<',         '<gv')
set('v', '>',         '>gv')
set('n', '<c-h>',     '<c-w>h')
set('n', '<c-j>',     '<c-w>j')
set('n', '<c-k>',     '<c-w>k')
set('n', '<c-l>',     '<c-w>l')
set('n', '<c-up>',    '<cmd>resize +5<cr>')
set('n', '<c-down>',  '<cmd>resize -5<cr>')
set('n', '<c-left>',  '<cmd>vertical resize -20<cr>')
set('n', '<c-right>', '<cmd>vertical resize +20<cr>')
set('n', '<c-w>+',    '<cmd>resize +5<cr>')
set('n', '<c-w>-',    '<cmd>resize -5<cr>')
set('n', '<c-w><',    '<cmd>vertical resize -20<cr>')
set('n', '<c-w>>',    '<cmd>vertical resize +20<cr>')
set('n', '-',         '<cmd>Ex<cr>')
