local b = require('utils.bind')

b.map('Y', 'yg_', 'Yank till end of line', { 'n', 'x' })
b.map('<Leader>p', '"+p', 'Paste from clipboard', { 'n', 'x', 'o' })
b.map('<Leader>P', '"+P', 'Paste from clipboard before cursor', { 'n', 'x', 'o' })
b.map('<Leader>y', '"+y', 'Yank to clipboard', { 'n', 'x', 'o' })
b.map('<Leader>Y', '"+yg_', 'Yank to clipboard till end of line', { 'n', 'x', 'o' })
b.map('<Esc>', '<Cmd>noh<CR><Esc>', 'Clear hls and <Esc>', { 'n', 'x', 'i', 's' })
b.map('<C-S>', '<Esc><Cmd>silent! update | redraw<CR>', 'Save', { 'n', 'i', 'x' })
b.map('j', "v:count == 0 ? 'gj' : 'j'", 'Go up one line', { 'n', 'x' }, { expr = true })
b.map('k', "v:count == 0 ? 'gk' : 'k'", 'Go down one line', { 'n', 'x' }, { expr = true })
b.xmap('p', 'P', 'Paste before cursor')
b.xmap('<', '<gv', 'Deindent selection')
b.xmap('>', '>gv', 'Indent selection')
b.nmap('<C-h>', '<C-w>h', 'Goto left window')
b.nmap('<C-j>', '<C-w>j', 'Goto window below')
b.nmap('<C-k>', '<C-w>k', 'Goto window above')
b.nmap('<C-l>', '<C-w>l', 'Goto right window')
b.nmap('<C-Down>', '<Cmd>resize -5<CR>', 'Decrease window height')
b.nmap('<C-Up>', '<Cmd>resize +5<CR>', 'Increase window height')
b.nmap('<C-Left>', '<Cmd>vertical resize -20<CR>', 'Decrease window width')
b.nmap('<C-Right>', '<Cmd>vertical resize +20<CR>', 'Increase window width')
b.tmap('<C-h>', b.term_send_esc('<C-h>'), 'Goto left window')
b.tmap('<C-j>', b.term_send_esc('<C-j>'), 'Goto window below')
b.tmap('<C-k>', b.term_send_esc('<C-k>'), 'Goto window above')
b.tmap('<C-l>', b.term_send_esc('<C-l>'), 'Goto right window')
b.tmap('<C-/>', '<cmd>close<cr>', 'Hide Terminal')
b.nmap('<Leader>b', b.create_scratch_buf, 'Open a scratch buffer')
