# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Change your personal monitor setup in here to keep the main config portable
source = ~/.config/hypr/monitors.conf

# Default applications
$terminal = alacritty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$passwordManager = 1password
$messenger = signal-desktop
$webapp = $browser --app

# Use defaults Omarchy defaults
source = ~/.local/share/omarchy/default/hypr/autostart.conf

# Autostart
exec-once = /usr/bin/pypr

source = ~/.local/share/omarchy/default/hypr/bindings.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf


# Extra autostart processes (uncomment to run Dropbox)
# exec-once = dropbox-cli start

# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Extra bindings (overwrite existing binding with: unbind = SUPER, O)

bind = SUPER, A, exec, $webapp="https://chatgpt.com"
bind = SUPER, X, exec, $webapp="https://grok.com"
unbind = SUPER, C
bind = SUPER, C, exec, $webapp="https://claude.ai/new"
bind = SUPER, E, exec, $webapp="https://app.hey.com"
bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER SHIFT, G, exec, $webapp="https://web.whatsapp.com/"
bind = SUPER ALT, G, exec, $webapp="https://messages.google.com/web/conversations"

unbind = , PRINT
bind = SUPER SHIFT, R, exec, hyprshot -m region

# Pypr - scratchpads
bind = SUPER SHIFT, L, exec, pypr toggle scratch_left_term
bind = SUPER SHIFT, J, exec, pypr toggle scratch_bottom_term
bind = SUPER SHIFT, K, exec, pypr toggle scratch_top_term
bind = SUPER SHIFT, H, exec, pypr toggle scratch_right_term

# Pypr - toggle special
unbind = SUPER, N
bind = SUPER, N, togglespecialworkspace, stash # toggles "stash" special workspace visibility
bind = SUPER SHIFT, N, exec, pypr toggle_special stash # moves window to/from the "stash" workspace

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Alt + Space
  kb_layout = us,us
  kb_variant = ,intl
  kb_options = compose:caps,grp:alt_space_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, class:Alacritty

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
