[pyprland]
plugins = ["scratchpads", "toggle_special"]

[scratchpads.scratch_top_term]
animation = "fromTop"
command = "alacritty --class=scratch_Top_term"
class = "scratch_Top_term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.scratch_bottom_term]
animation = "fromBottom"
command = "alacritty --class=scratch_Bottom_term"
class = "scratch_Bottom_term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.scratch_left_term]
animation = "fromLeft"
command = "alacritty --class=scratch_Left_term"
class = "scratch_Left_term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.scratch_right_term]
animation = "fromRight"
command = "alacritty --class=scratch_Right_term"
class = "scratch_Right_term"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50
