onboarding = false

[experimental]
kitty_graphics = true

[ui.toast]
delivery = "herdr"

[theme]
name = "one-dark"
auto_switch = false

[ui.sound]
enabled = true

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
sidebar_width = 36

[keys]
prefix = "ctrl+a"

workspace_picker = "alt+shift+f"
navigate_pane_left = "h"
navigate_pane_down = "j"
navigate_pane_up = "k"
navigate_pane_right = "l"

navigate_workspace_up = "ctrl+k"
navigate_workspace_down = "ctrl+j"
previous_agent = "ctrl+,"
next_agent = "ctrl+."
switch_tab = "alt+1..9"

new_workspace = "prefix+shift+n"
rename_workspace = "prefix+shift+r"
close_workspace = "prefix+shift+x"

detach = "prefix+q"
copy_mode = "prefix+y"
zoom = "prefix+z"
toggle_sidebar = "prefix+e"
resize_mode = "alt+shift+,"

swap_pane_left = "prefix+shift+h"
swap_pane_down = "prefix+shift+j"
swap_pane_up = "prefix+shift+k"
swap_pane_right = "prefix+shift+l"

goto = "alt+shift+g"
last_pane = "alt+shift+o"
focus_pane_left = "alt+shift+h"
focus_pane_down = "alt+shift+j"
focus_pane_up = "alt+shift+k"
focus_pane_right = "alt+shift+l"

new_tab = "alt+shift+c"
previous_tab = "alt+shift+p"
next_tab = "alt+shift+n"
rename_tab = "alt+shift+r"
close_tab = "alt+shift+x"

split_vertical = "alt+shift+v"
split_horizontal = "alt+shift+s"

new_worktree = ""
cycle_pane_next = ""
cycle_pane_previous = ""
close_pane = ""
remote_image_paste = ""

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"
description = "run lazygit"

[[keys.command]]
key = "prefix+v"
type = "pane"
command = "nvim"
description = "run nvim"

[[keys.command]]
key = "prefix+o"
type = "pane"
command = "lazydocker"
description = "run lazydocker"
