general {
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(dcd7ba)
    # col.active_border = rgb(c4a484)
    col.inactive_border = rgb(28282a)
}
