[[manager.prepend_keymap]]
   on = ["<C-s>"]
   exec = 'shell "$SHELL" --block --confirm'
   desc = "Open shell here" 
[[manager.prepend_keymap]]
   on = ["<Esc>"]
   exec = "close"
   desc = "Cancel input" 
[[manager.prepend_keymap]]
   on = ["l"]
   exec = "plugin --sync smart-enter"
   desc = "Smart enter" 
