font_size 11
font_family BerkeleyMono Nerd Font
bold_font BerkeleyMono Nerd Font Bold
italic_font BerkeleyMono Nerd Font Italic
bold_italic_font BerkeleyMono Nerd Font Bold Italic

# shell_integration no-cursor
confirm_os_window_close 0
enable_audio_bell no
hide_window_decorations no

cursor_shape block
cursor_blink_interval 0

# clear_all_shortcuts yes
# clear_all_mouse_actions yes

map f5 load_config_file

# mouse related features
# copy_on_select clipboard
# mouse_map left press grabbed mouse_selection normal
# mouse_map ctrl+left press grabbed mouse_selection rectangle
# mouse_map left doublepress grabbed mouse_selection word
# mouse_map left triplepress grabbed mouse_selection line
# mouse_map ctrl+left triplepress grabbed mouse_selection line_from_point
# mouse_map ctrl+right press grabbed mouse_selection extend
# mouse_map right release grabbed paste_selection

# copy/paste
map ctrl+shift+v paste_from_clipboard

# Keyboard shortcuts.
kitty_mod alt+shift

map ctrl+shift+equal change_font_size all +2.0
map ctrl+shift+minus change_font_size all -2.0

foreground            #D8DEE9
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #3B4252
color8   #4C566A

# red
color1   #BF616A
color9   #BF616A

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #81A1C1
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #B48EAD

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #ECEFF4
