# vim:fileencoding=utf-8:foldmethod=marker

# Theme

font_family      IosevkaTermNerdFontMono
bold_font        auto
italic_font      auto
bold_italic_font auto

enable_audio_bell no

font_size 13.0

cursor_shape block
cursor_shape_unfocused block
cursor_beam_thickness 3.0
cursor_blink_interval 0
shell_integration no-cursor

allow_remote_control yes
listen_on unix:@mykitty

# Keymaps

enabled_layouts splits:split_axis=horizontal,stack

# Vertical split, side-by-side
map alt+shift+v launch --cwd=current --location=vsplit
# Horizontal split, stacked
map alt+shift+s launch --cwd=current --location=hsplit
# Kill pane
map alt+shift+x close_window
# Pane navigation: prefix + arrows
map alt+shift+h neighboring_window left
map alt+shift+l neighboring_window right
map alt+shift+k neighboring_window up
map alt+shift+k neighboring_window down

# Resize mode: prefix R, then h/j/k/l or arrows, Esc to exit
map --new-mode resize --timeout 5.0 alt+shift+r
map --mode resize h     resize_window narrower 10
map --mode resize l     resize_window wider 10
map --mode resize k     resize_window taller 5
map --mode resize j     resize_window shorter 5
map --mode resize esc   pop_keyboard_mode
map --mode resize enter pop_keyboard_mode

# New window
map alt+shift+c new_tab_with_cwd
# Rename window
map alt+shift+, set_tab_title
# Kill window
map alt+shift+& close_tab
# Next / previous window
map alt+shift+n next_tab
map alt+shift+p previous_tab
# Choose window
map alt+shift+w select_tab
# Go to window
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
# Command palette, roughly "show available commands"
map alt+shift+/ command_palette
