font_size 11
font_family BerkeleyMono Nerd Font
bold_font BerkeleyMono Nerd Font Bold
italic_font BerkeleyMono Nerd Font Italic
bold_italic_font BerkeleyMono Nerd Font Bold Italic

# shell_integration no-cursor
confirm_os_window_close 0
enable_audio_bell no
hide_window_decorations no

cursor_shape block
cursor_blink_interval 0

map f5 load_config_file

# copy/paste
map ctrl+shift+v paste_from_clipboard

# Keyboard shortcuts.
kitty_mod alt+shift

map ctrl+shift+equal change_font_size all +0.5
map ctrl+shift+minus change_font_size all -0.5

background            #181818
