selection_foreground #000000
selection_background #ffffff

foreground #ffffff
background #000000

color0  #777755
color1  #aa9988
color2  #5f8787
color3  #99abaa
color4  #556677
color5  #c1c1c1
color6  #999999
color7  #c1c1c1
color8  #363636
color9  #aaaaaa
color10 #363636
color11 #000000
color12 #aaaaaa
color13 #888888
color14 #333333
color15 #444444

active_tab_foreground #ffffff
active_tab_background #000000
inactive_tab_foreground #666666
inactive_tab_background #000000

active_border_color #ffffff
